<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KR6B0UD" failures="1" tests="6" name="tests.BookingTest" time="63.371" errors="0" timestamp="2024-11-12T20:40:05 IST" skipped="5">
  <testcase classname="tests.BookingTest" name="cruises" time="0.000">
    <skipped/>
  </testcase> <!-- cruises -->
  <testcase classname="tests.BookingTest" name="menu" time="0.000">
    <skipped/>
  </testcase> <!-- menu -->
  <testcase classname="tests.BookingTest" name="newBooking" time="0.000">
    <skipped/>
  </testcase> <!-- newBooking -->
  <testcase classname="tests.BookingTest" name="csu" time="0.000">
    <skipped/>
  </testcase> <!-- csu -->
  <testcase classname="tests.BookingTest" name="login" time="63.371">
    <failure message="Test failed at login: Login failed due to incorrect credentials." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed at login: Login failed due to incorrect credentials.
at org.testng.Assert.fail(Assert.java:111)
at tests.BookingTest.login(BookingTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.BookingTest" name="agent" time="0.000">
    <skipped/>
  </testcase> <!-- agent -->
</testsuite> <!-- tests.BookingTest -->
